<?php
return '<!-- wp:genesis-custom-blocks/custom-genesis-hero-module {"background-type":"bg-gradient-black-1","background-media":0,"client-logo":0,"set-as-logo":false,"heading":"Lorem Ipsum","text-color":"text-white","sub-text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac ante luctus, bibendum purus nec, porttitor ex. Quisque sed tincidunt mauris. Nunc pharetra ipsum nibh, non convallis arcu tempus non.","button-text":"Watch Video","video-toggle":"videoModal","button-link":"https://vimeo.com/123456789","component-block-height":"hero-height"} /-->

<!-- wp:genesis-custom-blocks/custom-genesis-hero-module {"background-media":0,"client-logo":0,"set-as-logo":false,"heading":"","sub-heading":"Lorem Ipsum","text-color":"text-black","sub-text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac ante luctus, bibendum purus nec, porttitor ex. Quisque sed tincidunt mauris. Nunc pharetra ipsum nibh, non convallis arcu tempus non. ","button-text":"Explore more","button-link":"https://example.com/company/","button-theme":"dark-button","component-block-height":"compact-height","reverse-column":"align-right"} /-->

<!-- wp:genesis-custom-blocks/custom-genesis-multicard-w-text-module {"background-type":"bg-gradient-black-1","background-media":0,"heading":"Lorem Ipsum","text-color":"text-white","add-cards":{"rows":[{"":"","card-title":"Lorem Ipsum Marketplace","body-copy":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac ante luctus, bibendum purus nec, porttitor ex. Quisque sed tincidunt mauris. Nunc pharetra ipsum nibh, non convallis arcu tempus non. ","button-label":"Learn More","button-link-for-cta":{"0":"h","1":"t","2":"t","3":"p","4":"s","5":":","6":"/","7":"/","8":"c","9":"a","10":"p","11":"i","12":"t","13":"o","14":"l","15":"i","16":"s","17":"p","18":"r","19":"o","20":"d","21":".","22":"w","23":"p","24":"e","25":"n","26":"g","27":"i","28":"n","29":"e","30":".","31":"c","32":"o","33":"m","34":"/","35":"i","36":"n","37":"s","38":"i","39":"g","40":"h","41":"t","42":"s","43":"/","id":0,"name":""},"card-icon":5694,"anchor":"https://example.com/capital-marketplace/","open-link-in-new-tab":false},{"":"","card-title":"Portfolio Optimization","card-icon":5693,"body-copy":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac ante luctus, bibendum purus nec, porttitor ex. Quisque sed tincidunt mauris. Nunc pharetra ipsum nibh, non convallis arcu tempus non. ","button-label":"Learn More","button-link-for-cta":"https://example.com/insights/","open-link-in-new-tab":false,"anchor":"https://example.com/portfolio-compression/"}]}} /-->

<!-- wp:genesis-custom-blocks/custom-genesis-quick-info-stats {"background-type":"","text-color":"text-black","items":{"rows":[{"":"","stats-number":"100","after-text":"+","stats-description":"Quisque eget sem viverra, mattis massa vulputate "},{"":"","stats-number":"15","after-text":"T","previous-text":"$","stats-description":"Quisque eget sem viverra, mattis massa vulputate"}]},"button-text":"Learn More","button-link":""} /-->

<!-- wp:genesis-custom-blocks/custom-genesis-generic-slider {"background-type":"","background-media":0,"title":"Media","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac ante luctus, bibendum purus nec, porttitor ex. ","text-color":"text-black","rotate-interval":"","add-slider":{"rows":[{"":"","content":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac ante luctus, bibendum purus nec, porttitor ex. Quisque sed tincidunt mauris. Nunc pharetra ipsum nibh, non convallis arcu tempus non.  ","heading":"Lorem Ipsum","slider-icon":0,"slider-image":0,"slider-button":"Learn More","slider-link-for-cta":{"id":4968,"name":"Lorem Ipsum"}},{"":"","slider-image":0,"heading":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac ante luctus, bibendum purus nec, porttitor ex.","slider-button":"Learn More","slider-link-for-cta":{"id":4968,"name":"Lorem Ipsum"}}]}} /-->';
